import { useEffect, useState } from 'react';
import { Pencil, Plus, Trash2, X } from 'lucide-react';
import { periodRepository } from '../db/repositories/periodRepository';
import type { Period, PeriodType } from '../models/period';

const empty=(type:PeriodType='school'):Period=>{const now=new Date().toISOString();return{id:crypto.randomUUID(),name:'',type,startDate:new Date().toISOString().slice(0,10),endDate:new Date().toISOString().slice(0,10),color:'#6366f1',icon:'🗓️',description:'',createdAt:now,updatedAt:now}};
export function PeriodsPage(){
 const [periods,setPeriods]=useState<Period[]>([]);const [editing,setEditing]=useState<Period|null>(null);
 const load=()=>void periodRepository.getAll().then(setPeriods);useEffect(load,[]);
 const save=async()=>{if(!editing?.name.trim()||editing.endDate<editing.startDate)return;if(periods.some(p=>p.id===editing.id))await periodRepository.update(editing.id,editing);else await periodRepository.create(editing);setEditing(null);load()};
 const remove=async(p:Period)=>{if(confirm(`Eliminar "${p.name}"?`)){await periodRepository.remove(p.id);load()}};
 return <div className="page"><div className="page-heading"><div><h1>Períodos</h1><p>Escola, férias, viagens e ocasiões especiais.</p></div><button className="primary-btn" onClick={()=>setEditing(empty('holiday'))}><Plus size={17}/> Novo período</button></div><div className="period-grid">{periods.length?periods.map(p=><div className="period-card" key={p.id} style={{borderLeftColor:p.color}}><span className="period-icon">{p.icon??'🗓️'}</span><div><b>{p.name}</b><small>{p.startDate} → {p.endDate}</small><small>{p.type}</small></div><div className="card-actions"><button className="icon-btn" onClick={()=>setEditing(p)}><Pencil size={16}/></button><button className="icon-btn danger-icon" onClick={()=>remove(p)}><Trash2 size={16}/></button></div></div>):<div className="empty">Ainda não existem períodos.</div>}</div>{editing&&<div className="modal-backdrop"><div className="sheet"><div className="sheet-header"><div className="sheet-title">{periods.some(p=>p.id===editing.id)?'Editar período':'Novo período'}</div><button className="icon-btn" onClick={()=>setEditing(null)}><X/></button></div><label>Nome<input value={editing.name} onChange={e=>setEditing({...editing,name:e.target.value})} placeholder="Ex.: Férias de verão" autoFocus/></label><div className="form-grid"><label>Tipo<select value={editing.type} onChange={e=>setEditing({...editing,type:e.target.value as PeriodType})}><option value="school">Escola</option><option value="holiday">Férias</option><option value="trip">Viagem</option><option value="special">Especial</option><option value="custom">Personalizado</option></select></label><label>Ícone<input value={editing.icon??''} maxLength={2} onChange={e=>setEditing({...editing,icon:e.target.value})}/></label></div><div className="form-grid"><label>Início<input type="date" value={editing.startDate} onChange={e=>setEditing({...editing,startDate:e.target.value})}/></label><label>Fim<input type="date" value={editing.endDate} onChange={e=>setEditing({...editing,endDate:e.target.value})}/></label></div><label>Cor<input type="color" value={editing.color} onChange={e=>setEditing({...editing,color:e.target.value})}/></label><label>Descrição<textarea rows={3} value={editing.description??''} onChange={e=>setEditing({...editing,description:e.target.value})}/></label><div className="sheet-actions"><span/><button className="secondary-btn" onClick={()=>setEditing(null)}>Cancelar</button><button className="primary-btn" onClick={save}>Guardar</button></div></div></div>}</div>
}
