import { CalendarDays, ChevronLeft, ChevronRight, Plus, Clock3, CalendarRange, Settings, AlertTriangle, Repeat2 } from 'lucide-react';
import { addDays, addMonths, endOfMonth, endOfWeek, format, getDaysInMonth, startOfMonth, startOfWeek } from 'date-fns';
import { pt } from 'date-fns/locale';
import { useEffect, useMemo, useState } from 'react';
import type { Activity } from '../models/activity';
import type { Recurrence } from '../models/recurrence';
import { useActivityStore } from '../stores/activityStore';
import { useCatalogStore } from '../stores/catalogStore';
import { ActivityForm } from '../components/activity/ActivityForm';
import { activityStyle, toMinutes } from '../utils/time';
import { TodayPage } from '../pages/TodayPage';
import { PeriodsPage } from '../pages/PeriodsPage';
import { SettingsPage } from '../pages/SettingsPage';
import { db } from '../db/database';
import { expandActivitiesForRange } from '../services/recurrenceService';
import { findConflicts } from '../services/conflictService';
import { useSettingsStore } from '../stores/settingsStore';

type View='week'|'month'|'year'|'today'|'periods'|'settings';
type PrintView='week'|'month'|'year'|null;
export function App(){
 const [selectedDate,setSelectedDate]=useState(new Date());const [view,setView]=useState<View>('week');const [editing,setEditing]=useState<Activity|null>(null);const [creating,setCreating]=useState(false);const [recurrences,setRecurrences]=useState<Recurrence[]>([]);const [dragging,setDragging]=useState<string|null>(null);const [filter,setFilter]=useState('');const [printView,setPrintView]=useState<PrintView>(null);
 const activities=useActivityStore(s=>s.activities);const load=useActivityStore(s=>s.load);const reschedule=useActivityStore(s=>s.reschedule);const loadCatalog=useCatalogStore(s=>s.load);const settings=useSettingsStore(s=>s.settings);const loadSettings=useSettingsStore(s=>s.load);const weekStart=startOfWeek(selectedDate,{weekStartsOn:settings.weekStartsOn});
 const HOURS=useMemo(()=>Array.from({length:Math.max(1,settings.lastDayHour-settings.firstDayHour+1)},(_,i)=>i+settings.firstDayHour),[settings.firstDayHour,settings.lastDayHour]);
 const pxPerHour=72; const visibleStart= settings.firstDayHour*60; const visibleEnd=(settings.lastDayHour+1)*60;
 useEffect(()=>{void loadSettings()},[loadSettings]);
 useEffect(()=>{const root=document.documentElement; const theme=settings.theme==='system'?(window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):settings.theme; root.dataset.theme=theme},[settings.theme]);
 useEffect(()=>{void load();void loadCatalog();void db.recurrences.toArray().then(setRecurrences)},[load,loadCatalog]);
 useEffect(()=>{const done=()=>setPrintView(null);window.addEventListener('afterprint',done);return()=>window.removeEventListener('afterprint',done)},[]);
 const days=useMemo(()=>Array.from({length:7},(_,i)=>addDays(weekStart,i)),[weekStart]);
 const monthStart=startOfMonth(selectedDate); const monthEnd=endOfMonth(selectedDate);
 const monthGridStart=startOfWeek(monthStart,{weekStartsOn:settings.weekStartsOn}); const monthGridEnd=endOfWeek(monthEnd,{weekStartsOn:settings.weekStartsOn});
 const monthDays=useMemo(()=>{const arr:Date[]=[];for(let d=monthGridStart;d<=monthGridEnd;d=addDays(d,1))arr.push(d);return arr},[monthGridStart,monthGridEnd]);
 const displayed=useMemo(()=>expandActivitiesForRange(activities,recurrences,weekStart,addDays(weekStart,6)),[activities,recurrences,weekStart]);
 const monthDisplayed=useMemo(()=>expandActivitiesForRange(activities,recurrences,monthStart,monthEnd),[activities,recurrences,monthStart,monthEnd]);
 const filtered=useMemo(()=>{const q=filter.trim().toLocaleLowerCase('pt-PT');return q?displayed.filter(a=>`${a.title} ${a.location??''} ${a.notes??''}`.toLocaleLowerCase('pt-PT').includes(q)):displayed},[displayed,filter]);
 const conflictIds=useMemo(()=>new Set(filtered.filter(a=>findConflicts(a,filtered).length>0).map(a=>a.id)),[filtered]);
 const moveWeek=(n:number)=>setSelectedDate(addDays(selectedDate,n*7));const moveMonth=(n:number)=>setSelectedDate(addMonths(selectedDate,n));const moveYear=(n:number)=>setSelectedDate(addMonths(selectedDate,n*12));const openCreate=(date=selectedDate)=>{setSelectedDate(date);setCreating(true)};const nav=(v:View)=>{setView(v);if(v==='today')setSelectedDate(new Date())};
 const print=(v:PrintView)=>{setPrintView(v);window.setTimeout(()=>window.print(),80)};
 const category=(id?:string)=>useCatalogStore.getState().categories.find(c=>c.id===id);const drop=(e:React.DragEvent<HTMLDivElement>,day:Date)=>{e.preventDefault();const id=dragging;if(!id)return;const rect=e.currentTarget.getBoundingClientRect();const y=e.clientY-rect.top;const minutes=Math.max(visibleStart,Math.min(visibleEnd-15,visibleStart+Math.round(y/(pxPerHour/60)/15)*15));const original=activities.find(a=>a.id===id);if(!original)return;const duration=toMinutes(original.endTime)-toMinutes(original.startTime);const start=Math.floor(minutes/60).toString().padStart(2,'0')+':'+String(minutes%60).padStart(2,'0');const endMinutes=Math.min(visibleEnd,minutes+duration);const end=Math.floor(endMinutes/60).toString().padStart(2,'0')+':'+String(endMinutes%60).padStart(2,'0');void reschedule(id,format(day,'yyyy-MM-dd'),start,end);setDragging(null)};
 return <main className="app-shell">
 <header className="topbar"><div><div className="brand">WeekFlow</div><div className="subtitle">Planeador · V0.4</div></div><div className="topbar-actions"><button className="icon-btn" onClick={()=>print(view==='year'?'year':view==='month'?'month':'week')} title="Imprimir" aria-label="Imprimir"><span>🖨️</span></button><CalendarDays size={22}/></div></header>
 <section className="view-toolbar">
   <div className="view-switcher">{(['week','month','year'] as const).map(v=><button key={v} className={view===v?'active':''} onClick={()=>setView(v)}>{v==='week'?'Semana':v==='month'?'Mês':'Ano'}</button>)}</div>
   <div className="print-actions"><button className="secondary-btn compact-btn" onClick={()=>print('week')}>🖨 Semana</button><button className="secondary-btn compact-btn" onClick={()=>print('month')}>🖨 Mês</button><button className="secondary-btn compact-btn" onClick={()=>print('year')}>🖨 Ano</button></div>
 </section>
 {view==='week'&&<><section className="week-toolbar"><button onClick={()=>moveWeek(-1)} aria-label="Semana anterior"><ChevronLeft/></button><button className="today-button" onClick={()=>setSelectedDate(new Date())}>{format(weekStart,'d MMM',{locale:pt})} — {format(addDays(weekStart,6),'d MMM yyyy',{locale:pt})}</button><button onClick={()=>moveWeek(1)} aria-label="Semana seguinte"><ChevronRight/></button></section><section className="feature-strip"><span><Repeat2 size={16}/> Recorrências: {recurrences.length}</span><span><AlertTriangle size={16}/> Conflitos: {Math.ceil(conflictIds.size/2)}</span><label className="calendar-search"><input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Pesquisar atividades…" aria-label="Pesquisar atividades"/></label></section><section className="calendar"><div className="time-column"><div className="corner"/>{HOURS.map(h=><div className="time-label" key={h}>{String(h).padStart(2,'0')}:00</div>)}</div><div className="days-grid">{days.map(day=>{const key=format(day,'yyyy-MM-dd');const dayActivities=filtered.filter(a=>a.date===key);return <div className={`day-column ${key===format(selectedDate,'yyyy-MM-dd')?'selected':''}`} key={key} onClick={()=>setSelectedDate(day)}><div className="day-header"><span>{format(day,'EEE',{locale:pt}).slice(0,3)}</span><strong>{format(day,'d')}</strong></div><div className="day-body" style={{height:HOURS.length*pxPerHour}} onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,day)}>{HOURS.map(h=><div className="hour-cell" key={h} onDoubleClick={()=>openCreate(day)}/>) }{dayActivities.map(a=>{const st=activityStyle(a.startTime,a.endTime,visibleStart,pxPerHour);const conflicts=conflictIds.has(a.id);const cat=category(a.categoryId);const recurring=Boolean(a.recurrenceId);const realId=a.id.includes('__')?a.id.split('__')[0]:a.id;return <button draggable={!recurring} onDragStart={()=>setDragging(realId)} onDragEnd={()=>setDragging(null)} className={`activity-card ${a.completed?'completed':''} ${conflicts?'conflict':''} ${recurring?'recurring':''}`} style={{...st,backgroundColor:cat?.color??a.color}} key={a.id} onClick={e=>{e.stopPropagation();setEditing(activities.find(x=>x.id===realId)??a)}} title={conflicts?'Conflito de horário':''}><span>{a.icon??'📅'}</span><b>{a.title}</b><small>{a.startTime}–{a.endTime}{cat?` · ${cat.name}`:''}{recurring?' · ↻':''}</small></button>})}</div></div>})}</div></section></>}
 {view==='month'&&<MonthView selectedDate={selectedDate} days={monthDays} activities={monthDisplayed} category={category} onPrev={()=>moveMonth(-1)} onNext={()=>moveMonth(1)} onToday={()=>setSelectedDate(new Date())} onSelect={setSelectedDate} onEdit={setEditing}/>}
 {view==='year'&&<YearView selectedDate={selectedDate} activities={activities} recurrences={recurrences} onPrev={()=>moveYear(-1)} onNext={()=>moveYear(1)} onToday={()=>setSelectedDate(new Date())} onSelect={d=>{setSelectedDate(d);setView('month')}}/>}
 {view==='today'&&<TodayPage onEdit={setEditing}/>} {view==='periods'&&<PeriodsPage/>} {view==='settings'&&<SettingsPage/>}
 <button className="fab" onClick={()=>openCreate()} aria-label="Adicionar atividade"><Plus size={26}/></button><nav className="bottom-nav"><button className={view==='week'?'active':''} onClick={()=>nav('week')}><CalendarDays/><span>Semana</span></button><button className={view==='month'?'active':''} onClick={()=>nav('month')}><CalendarRange/><span>Mês</span></button><button className={view==='today'?'active':''} onClick={()=>nav('today')}><Clock3/><span>Hoje</span></button><button className={view==='settings'?'active':''} onClick={()=>nav('settings')}><Settings/><span>Definições</span></button></nav>
 {printView&&<PrintLayout view={printView} selectedDate={selectedDate} activities={activities} recurrences={recurrences} category={category} settings={settings}/>}
 {(creating||editing)&&<ActivityForm date={editing?.date??format(selectedDate,'yyyy-MM-dd')} activity={editing} onClose={()=>{setCreating(false);setEditing(null);void load();void db.recurrences.toArray().then(setRecurrences)}}/>}</main>
}

function MonthView({selectedDate,days,activities,category,onPrev,onNext,onToday,onSelect,onEdit}:{selectedDate:Date;days:Date[];activities:Activity[];category:(id?:string)=>any;onPrev:()=>void;onNext:()=>void;onToday:()=>void;onSelect:(d:Date)=>void;onEdit:(a:Activity)=>void}){
 const names=['dom','seg','ter','qua','qui','sex','sáb'];
 return <section className="month-page"><div className="period-toolbar"><button onClick={onPrev}><ChevronLeft/></button><button className="today-button" onClick={onToday}>{format(selectedDate,'MMMM yyyy',{locale:pt})}</button><button onClick={onNext}><ChevronRight/></button></div><div className="month-grid">{names.map(n=><div className="month-weekday" key={n}>{n}</div>)}{days.map(day=>{const key=format(day,'yyyy-MM-dd');const items=activities.filter(a=>a.date===key);return <button className={`month-cell ${day.getMonth()!==selectedDate.getMonth()?'outside':''}`} key={key} onClick={()=>onSelect(day)}><strong>{format(day,'d')}</strong><div>{items.slice(0,4).map(a=><span key={a.id} className="month-item" onClick={e=>{e.stopPropagation();onEdit(a)}}><i style={{backgroundColor:category(a.categoryId)?.color??a.color}}/>{a.startTime} {a.title}</span>)}{items.length>4&&<small>+{items.length-4} mais</small>}</div></button>})}</div></section>
}

function YearView({selectedDate,activities,recurrences,onPrev,onNext,onToday,onSelect}:{selectedDate:Date;activities:Activity[];recurrences:Recurrence[];onPrev:()=>void;onNext:()=>void;onToday:()=>void;onSelect:(d:Date)=>void}){
 return <section className="year-page"><div className="period-toolbar"><button onClick={onPrev}><ChevronLeft/></button><button className="today-button" onClick={onToday}>{format(selectedDate,'yyyy')}</button><button onClick={onNext}><ChevronRight/></button></div><div className="year-grid">{Array.from({length:12},(_,m)=>{const month=addMonths(new Date(selectedDate.getFullYear(),0,1),m);const start=startOfMonth(month);const end=endOfMonth(month);const days=Array.from({length:getDaysInMonth(month)},(_,i)=>addDays(start,i));return <button className="mini-month" key={m} onClick={()=>onSelect(month)}><b>{format(month,'MMMM',{locale:pt})}</b><div className="mini-weekdays">{['D','S','T','Q','Q','S','S'].map((d,i)=><span key={i}>{d}</span>)}</div><div className="mini-days">{Array.from({length:start.getDay()===0?0: start.getDay()},()=>null).map((_,i)=><span className="empty-day" key={'e'+i}/>) }{days.map(d=><span key={d.toISOString()} className={activities.some(a=>a.date===format(d,'yyyy-MM-dd'))||recurrences.some(r=>r.startDate===format(d,'yyyy-MM-dd'))?'has-activity':''}>{format(d,'d')}</span>)}</div></button>})}</div></section>
}

function PrintLayout({view,selectedDate,activities,recurrences,category,settings}:{view:PrintView;selectedDate:Date;activities:Activity[];recurrences:Recurrence[];category:(id?:string)=>any;settings:any}){
 if(!view)return null;
 const expand=(start:Date,end:Date)=>expandActivitiesForRange(activities,recurrences,start,end);
 if(view==='week'){const start=startOfWeek(selectedDate,{weekStartsOn:settings.weekStartsOn});const days=Array.from({length:7},(_,i)=>addDays(start,i));const items=expand(start,addDays(start,6));return <div className="print-root print-week"><h1>WeekFlow · Semana</h1><h2>{format(start,'d MMM',{locale:pt})} — {format(addDays(start,6),'d MMM yyyy',{locale:pt})}</h2><div className="print-week-grid">{days.map(d=><div key={d.toISOString()}><h3>{format(d,'EEE d MMM',{locale:pt})}</h3>{items.filter(a=>a.date===format(d,'yyyy-MM-dd')).sort((a,b)=>a.startTime.localeCompare(b.startTime)).map(a=><div className="print-event" key={a.id}><b>{a.startTime}–{a.endTime}</b> {a.icon??'📅'} {a.title}{category(a.categoryId)?` · ${category(a.categoryId).name}`:''}</div>)}</div>)}</div></div>}
 if(view==='month'){const start=startOfMonth(selectedDate);const end=endOfMonth(selectedDate);const gridStart=startOfWeek(start,{weekStartsOn:settings.weekStartsOn});const gridEnd=endOfWeek(end,{weekStartsOn:settings.weekStartsOn});const days:Date[]=[];for(let d=gridStart;d<=gridEnd;d=addDays(d,1))days.push(d);const items=expand(start,end);const weekdays=['dom','seg','ter','qua','qui','sex','sáb'];return <div className="print-root print-month"><h1>WeekFlow · {format(selectedDate,'MMMM yyyy',{locale:pt})}</h1><div className="print-month-grid">{weekdays.map(w=><div className="print-month-weekday" key={w}>{w}</div>)}{days.map(d=><div className={`print-month-day ${d.getMonth()!==selectedDate.getMonth()?'outside':''}`} key={d.toISOString()}><b>{format(d,'d')}</b>{items.filter(a=>a.date===format(d,'yyyy-MM-dd')).sort((a,b)=>a.startTime.localeCompare(b.startTime)).slice(0,6).map(a=><div key={a.id}>{a.startTime} {a.title}</div>)}</div>)}</div></div>}
 const year=selectedDate.getFullYear();return <div className="print-root print-year"><h1>WeekFlow · {year}</h1><div className="print-year-grid">{Array.from({length:12},(_,m)=>{const month=new Date(year,m,1);const start=startOfMonth(month);const end=endOfMonth(month);const ds=Array.from({length:getDaysInMonth(month)},(_,i)=>addDays(start,i));const items=expand(start,end);return <div className="print-mini" key={m}><h3>{format(month,'MMMM',{locale:pt})}</h3><div className="print-mini-days">{ds.map(d=><span className={items.some(a=>a.date===format(d,'yyyy-MM-dd'))?'has-activity':''} key={d.toISOString()}>{format(d,'d')}</span>)}</div></div>})}</div></div>
}
